### ISSUE TITLE
stuff

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/capstone_wrapper#1]
tl;dr replace `cs_disasm` with `cs_disasm_iter` so that memory is only allocated **once**, rather than every time Disassemble is called. http://www.capstone-engine.org/iteration.html

```
Capstone::Capstone()
{
    mInstr = cs_malloc(mHandle);
    mSuccess = false;
}

Capstone::~Capstone()
{
    if(mInstr) //free last disassembled instruction
        cs_free(mInstr, 1);
}

bool Capstone::Disassemble(size_t addr, const unsigned char* data, int size)
{
    if(!data)
        return false;

    size_t codeSize = size;
    uint64_t addr64 = addr;

    return mSuccess = cs_disasm_iter(mHandle, (const uint8_t **)&data, &codeSize, &addr64, mInstr);
}
```

I'd commit it directly, but an update to `capstone_x**.lib` is required. It'll be easier to do this and switch to capstone next at the same time. (I don't feel like compiling it)

**Comment by mrexodia** [comment]
Okay, I'll push my capstone next branch.

**Comment by Nukem9** [comment]
https://github.com/x64dbg/capstone_wrapper/commit/17563a7a411abf1e0a70f80d38b6b30da33449b8
